---
title: "Using Bio Signals to Predict Smoker Status"
shorttitle: "Paper"
abstract: An Abstract
keywords: [health, data science]
thanks: Thanks to everyone for checking this out.
reference-section-title: References
bibliography: ../bibliography/project.bib
csl: ../bibliography/apa.csl
format:
  aog-article-pdf:
    keep-tex: false
    include-in-header: 
      text: |
        \usepackage{dcolumn}
#  submittable-pdf:
#     keep-tex: false
#     fig-pos: "!t"
#     include-in-header: 
#       text: |
#         \usepackage{dcolumn}
  submittable-docx: default
---

```{r}
#| label: setup
#| include: false
library(here)
source(here("utils","check_packages.R"))
source(here("utils","functions.R"))
```

# Introduction

Using various health indicator information classification models are utilized to predict smoker status. As it stands more than 16 million american are currently living with a disease that can be linked to smoking @noauthor_health_2022. The use of a model like this is application in public health especially when identifying links between certain bio signals and smoking status.

# Description of Data

The data for this project was collected from an online competition hosted on the Kaggle website called, "Binary Prediction of Smoker Status using Bio-Signals" @noauthor_binary_nodate. The training data was generated from a deep learning model that was generated from the "Smoker Status Prediction using Bio-Signals" data set @noauthor_smoker_nodate. The data set consist of 22 different predictors that range from age and height to health indicators like cholesterol level, hemoglobin and systolic pressure.

# Model Description

Using the training data set three different models were created which include a generalized linear mode

| Model                                   | Log Loss  | AROC      |
|-----------------------------------------|-----------|-----------|
| GLM                                     | 0.491946  | 0.8383444 |
| Classification Model with Ridge Penalty | 0.4951833 | 0.8350144 |
| Classification Model with Lasso Penalty | 0.4919702 | 0.8382552 |

: Model Performance Evaluation

# Data Visualization

# Conclusion

@fig-logistic-lasso
